
const companies = [
    "Varopakorn Public Co., Ltd.",
    "Alucon Public Company Limited",
    "Thai Beverage Can Limited",
    "Nikkei Siam Aluminium Limited",
    "UACJ (Thailand) Co., Ltd.",
    "SCG Packaging Public Company Limited",
    "Amcor Flexibles Thailand",
    "Huhtamaki Thailand",
    "Constantia Flexibles Thailand",
    "Tetra Pak Thailand",
    "Unifoil Thailand Co., Ltd.",
    "Star-Up Co., Ltd.",
    "Pick Pack Packaging Co., Ltd.",
    "Loften (Thailand) Co., Ltd.",
    "Poly Protech Co., Ltd.",
    "Standard Can Co. Ltd.",
    "Asia Can Co., Ltd.",
    "A.Best Inter Products Co., Ltd.",
    "Foil Packaging Co., Ltd.",
    "Royal Inter Pack Co., Ltd.",
    "Brilliant Intertrade Co., Ltd.",
    "Thai Union Group PCL",
    "Sea Value PLC",
    "Pataya Food Industries Ltd.",
    "Kuang Pei San Food Products Public Co., Ltd.",
    "King Pac Industrial Co., Ltd.",
    "TPBI Public Company Limited",
    "Eka Global",
    "Berry Global Thailand",
    "Toyo Aluminium Thailand",
    "Thung Hua Sinn Group",
    "Thai Plaspac Public Company Limited",
    "Sealed Air Thailand",
    "Mondi Thailand",
    "Southeast Asian Packaging and Canning Ltd.",
    "B.K. Aluminium Co., Ltd.",
    "UAC Global Public Company Limited",
    "Delta Aluminum Thailand Co., Ltd.",
    "Dingheng New Materials Co Ltd",
    "Union Inta Co Ltd",
    "Specialties Co., Ltd.",
    "N & N Foods Co., Ltd.",
    "Polyplex Thailand Public Co., Ltd.",
    "AJ Plast Public Company Limited",
    "The Metropolitan Metal Co., Ltd.",
    "Muang Thong Aluminium Industry Co., Ltd.",
    "Siam Aluminum",
    "Thai Aluminum",
    "V.P. Wood & Aluminum",
    "K.C. Aluminum",
    "S.P. Metal",
    "T.M.T. Aluminum",
    "Diamond Foil",
    "Sun Foil",
    "Vexcel Pack Co., Ltd.",
    "Plaloc Asia (Thailand) Co., Ltd.",
    "Siam Packaging",
    "Thai FlexPack",
    "Citic Metal Manufacturing Co., Ltd.",
    "AluminumRock",
    "Winsight",
    "Prepack Thailand Co., Ltd.",
    "Siam Food Products Public Company Limited",
    "Thai Agri Foods Public Company Limited",
    "Tropical Canning Thailand Public Co., Ltd.",
    "Narong Seafood Co., Ltd.",
    "Chotiwat Manufacturing Co., Ltd.",
    "Asian Alliance International Public Co., Ltd.",
    "A.S.P. Packaging Co., Ltd.",
    "P.K. Packaging Co., Ltd.",
    "Viboonkiat Packaging Co., Ltd.",
    "Advance Thailand Co., Ltd.",
    "Thai Nam Poly Pack Co., Ltd.",
    "Prestige Packaging Co., Ltd.",
    "BKK Containers Co., Ltd.",
    "Thai Containers Group Co., Ltd.",
    "Dynapack Thailand Co., Ltd.",
    "Packaging Solutions Thailand",
    "Thai Poly Pack",
    "Thai Foil",
    "Foil Thai",
    "Best Foil Co., Ltd.",
    "Siam Foil Co., Ltd.",
    "K.C.P. Aluminum Co., Ltd.",
    "T.A.C. Aluminum",
    "T.B.C. Ball Beverage Can Holdings Limited",
    "Winsome Aluminum",
    "Global Venture Solutions Co., Ltd.",
    "M A Mag Group Co Ltd",
    "Chor Thai Rungrueng",
    "Chonburi S J Co., Ltd.",
    "Alupact Create Hi Quality Co., Ltd.",
    "Varapakorn",
    "Daiki Aluminium Industry Thailand",
    "Nikkei MC Aluminium Thailand",
    "V.M.C. Aluminum",
    "Thai Metal Aluminium Co., Ltd.",
    "S.M.A. Aluminum",
    "Gold Foil Thailand",
    "Silver Foil Thailand"
];

console.log(JSON.stringify(companies));
