#!/usr/bin/env python3
"""Build static, bilingual cushion pages. No framework or checkout migration.

Run from any directory with Python 3. Rebuilding is idempotent. The owner-supplied
photo derivatives live in assets/cushions; data/cushions.json is the catalog source.
Legacy sofa details and original catalog cards are never regenerated by this script.
"""
import html
import json
import re
from pathlib import Path
from urllib.parse import urlencode

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'data/cushions.json').read_text())
PRODUCTS = DATA['products']
ORIGIN = 'https://weieryang.com'
PREVIEW = 'https://weieryang-cushions.yhsj98251.chatgpt.site'


def esc(value):
    return html.escape(str(value), quote=True)


def read(path):
    return (ROOT / path).read_bytes().decode('utf-8')


def write(path, content):
    dest = ROOT / path
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(content.encode('utf-8'))


def tr(lang, en, ru):
    return ru if lang == 'ru' else en


def category_path(lang):
    return ('/ru' if lang == 'ru' else '') + '/window-seat-cushions/'


def product_path(product, lang):
    return ('/ru' if lang == 'ru' else '') + '/products/' + product['slug'] + '/'


def photo(asset, alt, hero=False):
    source = '/assets/cushions/' + asset
    return (f'<img src="{source}-800.webp" srcset="{source}-400.webp 400w, {source}-800.webp 800w, {source}-1200.webp 1200w" '
            f'sizes="(max-width: 680px) calc(100vw - 48px), (max-width: 960px) 50vw, 560px" '
            f'alt="{esc(alt)}" width="1200" height="1200" decoding="async" '
            + ('fetchpriority="high" loading="eager"' if hero else 'loading="lazy"') + '>')


def schema(data):
    return '<script type="application/ld+json">' + json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/') + '</script>'


def alternates(en, ru):
    return '\n'.join(f'<link rel="alternate" hreflang="{lang}" href="{ORIGIN}{path}">' for lang, path in [('en', en), ('ru', ru), ('x-default', en)])


def head(lang, path, title, description, image, structured, en, ru, product=False):
    return f'''<!doctype html>
<html lang="{lang}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<meta name="robots" content="index, follow, max-image-preview:large">
<link rel="canonical" href="{ORIGIN}{path}">
{alternates(en, ru)}
<meta property="og:site_name" content="Weieryang"><meta property="og:type" content="{'product' if product else 'website'}">
<meta property="og:locale" content="{'ru_RU' if lang == 'ru' else 'en_US'}">
<meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{ORIGIN}{path}"><meta property="og:image" content="{ORIGIN}/assets/cushions/{image}-1200.webp">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{esc(title)}">
<meta name="twitter:description" content="{esc(description)}"><meta name="twitter:image" content="{ORIGIN}/assets/cushions/{image}-1200.webp">
{schema(structured)}
<link rel="icon" type="image/png" href="/assets/images/weieryang-favicon-32.png">
<link rel="stylesheet" href="/assets/factory-site.css?v=20260613d">
<link rel="stylesheet" href="/assets/product-system.css?v=20260613d">
<link rel="stylesheet" href="/assets/en-editorial.css?v=20260917a">
<link rel="stylesheet" href="/assets/cushion-catalog.css?v=20261006a">
<script defer src="/assets/factory-site.js?v=20261004a"></script>
<script defer src="/assets/site-analytics.js?v=20260916d"></script>
</head><body lang="{lang}" class="factory-v2 product-page editorial-en wy-cushion-page">
<a class="skip-link" href="#main-content">{tr(lang, 'Skip to content', 'К содержанию')}</a>'''


def header(lang, other, current=None):
    home = '/ru/' if lang == 'ru' else '/'
    products = '/ru/products/' if lang == 'ru' else '/products/'
    current = current or category_path(lang)
    products_current = ' aria-current="page"' if current == products else ''
    category_current = ' aria-current="page"' if current == category_path(lang) else ''
    return f'''<div class="topbar inner-topbar"><div class="shell topbar-inner"><span>{tr(lang, 'Weieryang · Sofas & custom window seat cushions', 'Weieryang · Диваны и подушки для подоконника')}</span><a href="mailto:tangkelian@weieryang.com">tangkelian@weieryang.com</a></div></div>
<header class="site-header inner-header"><div class="shell header-inner">
<a class="brand" href="{home}" aria-label="{tr(lang, 'Weieryang homepage', 'Главная Weieryang')}"><span class="brand-mark"><img src="/assets/images/weieryang-brand-logo-180.webp" alt="" width="72" height="54"></span><span class="brand-copy"><strong>Weieryang</strong><small>{tr(lang, 'Sofas & custom cushions', 'Диваны и подушки')}</small></span></a>
<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav" aria-label="{tr(lang, 'Open menu', 'Открыть меню')}"><span></span><span></span><span></span></button>
<nav class="main-nav" id="main-nav" aria-label="{tr(lang, 'Primary navigation', 'Основная навигация')}"><a href="{home}">{tr(lang, 'Factory', 'Главная')}</a><a href="{products}"{products_current}>{tr(lang, 'All products', 'Все товары')}</a><a href="{category_path(lang)}"{category_current}>{tr(lang, 'Window Seat Cushions', 'Подушки на подоконник')}</a><a class="text-link" href="{other}" lang="{tr(lang, 'ru', 'en')}" hreflang="{tr(lang, 'ru', 'en')}">{tr(lang, 'RU', 'EN')}</a></nav>
<div class="header-actions"><a class="button button-dark button-small" href="#quote">{tr(lang, 'Request a quote', 'Запросить цену')}</a></div>
</div></header>'''


def footer(lang):
    return f'''</main><footer class="wy-footer"><div class="shell"><div><strong>Weieryang</strong><p>Wuhan, China · © <span id="year">2026</span></p></div><nav aria-label="{tr(lang, 'Footer navigation', 'Навигация внизу страницы')}"><a href="{tr(lang, '/products/', '/ru/products/')}">{tr(lang, 'All products', 'Все товары')}</a><a href="{category_path(lang)}">{tr(lang, 'Window seat cushions', 'Подушки на подоконник')}</a><a href="{tr(lang, '/contact/', '/ru/contact/')}">{tr(lang, 'Contact', 'Контакты')}</a><a href="mailto:tangkelian@weieryang.com">Email</a></nav></div></footer></body></html>'''


def breadcrumb(items, lang):
    body = '<span aria-hidden="true">/</span>'.join(f'<a href="{path}">{esc(label)}</a>' if i < len(items) - 1 else f'<span aria-current="page">{esc(label)}</span>' for i, (path, label) in enumerate(items))
    return f'<nav class="breadcrumb" aria-label="{tr(lang, "Breadcrumb", "Навигационная цепочка")}">{body}</nav>'


def breadcrumb_schema(items):
    return {'@type': 'BreadcrumbList', 'itemListElement': [{'@type': 'ListItem', 'position': i + 1, 'name': label, 'item': ORIGIN + path} for i, (path, label) in enumerate(items)]}


def preview_url(product, lang):
    build = {'mode': 'custom', 'unit': tr(lang, 'in', 'cm'), 'market': tr(lang, 'US', 'RU'), 'length': None, 'width': None, 'thickness': None, 'stylePreference': product['style']}
    params = {'entry': 'catalog-' + product['reference'].lower(), 'configuration': json.dumps({'version': 1, 'build': build, 'drafts': {}}, separators=(',', ':'))}
    return PREVIEW + tr(lang, '/', '/ru/') + '?' + urlencode(params)


def quote_section(lang, product=None):
    name = product[lang]['name'] if product else tr(lang, 'Window seat cushion', 'Подушка на подоконник')
    ref = product['reference'] if product else ''
    body = tr(lang, f'Hello Weieryang, please quote {name} {ref}.\nLength:\nWidth / depth:\nFinished thickness:\nFront drop, if needed:\nPreferred photo / color:\nQuantity:\nDestination country and postal code:\nPlease confirm fabric, foam, item price, shipping and production time.', f'Здравствуйте! Прошу рассчитать {name} {ref}.\nДлина:\nШирина / глубина:\nТолщина сиденья:\nВысота свисающего края, если нужен:\nФото / цвет:\nКоличество:\nСтрана и почтовый индекс:\nПрошу подтвердить ткань, наполнитель, цену, доставку и срок изготовления.')
    email = 'mailto:tangkelian@weieryang.com?' + urlencode({'subject': f'{name} {ref} — quote request', 'body': body}).replace('+', '%20')
    whatsapp = 'https://wa.me/8613317178019?' + urlencode({'text': body})
    preview = f'<p><a href="{esc(preview_url(product, lang))}">{tr(lang, "Open customization preview with this design", "Открыть настройку с выбранным дизайном")} →</a></p>' if product else ''
    return f'''<section class="wy-cushion-section wy-tinted" id="quote"><div class="shell wy-cushion-grid"><div><p class="eyebrow">{tr(lang, 'Your measurements, your quote', 'Ваши размеры — ваш расчет')}</p><h2>{tr(lang, 'Tell us about your window seat.', 'Расскажите о вашем сиденье у окна.')}</h2><p>{tr(lang, 'Send the design reference, length, seat depth, finished thickness, quantity and delivery country / postal code. For an angled seat, add a dimensioned sketch. Your quote will confirm the cushion specification, item price, shipping charge and production time before payment.', 'Укажите дизайн, длину, глубину сиденья, толщину, количество, страну и почтовый индекс. Для сложной формы приложите эскиз с размерами. Перед оплатой в предложении подтверждаются спецификация, цена товара, стоимость доставки и срок изготовления.')}</p></div><div class="wy-quote-panel"><h3>{esc(name)} {ref}</h3><p>{tr(lang, 'Custom sizes are quoted individually. For a standard-size request, send the size you need so availability can be checked. Shipping to the United States or Russia and the available payment method are confirmed for the destination.', 'Нестандартный размер рассчитывается индивидуально. Для стандартного размера укажите нужные параметры, чтобы проверить наличие. Возможность доставки в США или Россию и способ оплаты подтверждаются для конкретного адреса.')}</p><div class="product-actions"><a class="button button-dark" href="{esc(email)}">{tr(lang, 'Prepare email inquiry', 'Подготовить запрос по email')}</a><a class="button button-light" href="{esc(whatsapp)}" target="_blank" rel="noopener noreferrer">WhatsApp</a></div>{preview}<p class="wy-photo-caption">{tr(lang, 'Quotation first. Photo-based designs have no confirmed online price yet.', 'Сначала расчет. Онлайн-цена вариантов по фото пока не подтверждена.')}</p></div></div></section>'''


def card(product, lang, legacy=False):
    p = product[lang]
    return f'''<article class="catalog-card family-card wy-cushion-card" data-product-card data-category="window-seat-cushions" data-search="{esc((product['reference'] + ' ' + p['name'] + ' custom bay window bench cushion ' + p['appearance']).lower())}">
<a href="{product_path(product, lang)}"><div class="catalog-image">{photo(product['style'], p['alt'])}<span class="catalog-category">{tr(lang, 'Window seat cushion', 'Подушка на подоконник')}</span></div><div class="catalog-card-copy"><div class="catalog-card-heading"><div><h2>{esc(p['short'])}</h2><p class="catalog-card-name">{product['reference']}</p></div><span class="catalog-arrow" aria-hidden="true">↗</span></div><p class="family-description">{esc(p['description'])}</p></div></a><div class="catalog-card-copy catalog-card-actions"><a class="button button-light" href="{product_path(product, lang)}">{tr(lang, 'View design', 'Посмотреть дизайн')}</a><a class="button button-dark" href="{product_path(product, lang)}#quote">{tr(lang, 'Request a quote', 'Запросить цену')}</a></div></article>'''


def measurement(lang):
    steps = [
        (tr(lang, 'Measure the seating area', 'Измерьте сиденье'), tr(lang, 'Measure the usable length and depth on the bench, in inches or centimeters. For a bay window, record front and back widths plus angled edges; include a sketch or template.', 'Измерьте полезную длину и глубину скамьи в сантиметрах или дюймах. Для эркера укажите переднюю и заднюю ширину и наклонные стороны; добавьте эскиз или шаблон.')),
        (tr(lang, 'Separate thickness and drop', 'Разделите толщину и свисающий край'), tr(lang, 'Choose the finished cushion thickness separately from any decorative front drop. Check the height against windows, handles, drawers and the intended sitting position.', 'Толщину подушки и высоту декоративного свисающего края указывайте отдельно. Проверьте высоту относительно окна, ручек, ящиков и удобного положения сидя.')),
        (tr(lang, 'Confirm the complete quote', 'Подтвердите полный расчет'), tr(lang, 'Send your preferred photo, color, quantity and postal code. Confirm fabric, foam, price, shipping and production time before approving the order.', 'Пришлите выбранное фото, цвет, количество и почтовый индекс. До заказа подтвердите ткань, наполнитель, цену, доставку и срок изготовления.')),
    ]
    return f'<section class="wy-cushion-section" id="measure"><div class="shell"><p class="eyebrow">{tr(lang, "Sizing guide", "Как снять размеры")}</p><h2>{tr(lang, "How to measure a custom window seat cushion", "Как измерить подушку для подоконника")}</h2><ol class="wy-step-list">' + ''.join(f'<li><h3>{a}</h3><p>{b}</p></li>' for a, b in steps) + '</ol></div></section>'


def questions(lang, product=None):
    qa = []
    if product:
        qa.append((product[lang]['question'], product[lang]['answer']))
    qa += [
        (tr(lang, 'Can I request a standard size or a custom size?', 'Можно запросить стандартный размер или размер на заказ?'), tr(lang, 'Both can be discussed. Send your required dimensions. Standard-size stock and final custom specifications must be confirmed in the quotation; the photo is not a size or stock guarantee.', 'Можно обсудить оба варианта. Пришлите нужные размеры. Наличие стандартного размера и параметры индивидуального заказа подтверждаются в предложении; фото не гарантирует размер или наличие.')),
        (tr(lang, 'What determines the cushion price?', 'От чего зависит цена подушки?'), tr(lang, 'The quoted specification includes length, depth, thickness, shape, fabric, foam, front edge and quantity. Shipping is checked separately for the destination. A photo design is not priced by the sofa packing data or a generic cushion estimate.', 'В расчет входят длина, глубина, толщина, форма, ткань, наполнитель, передний край и количество. Доставка рассчитывается отдельно по адресу. Цена варианта по фото не определяется упаковочными данными дивана или общим калькулятором.')),
        (tr(lang, 'Is the cover removable, washable or suitable for outdoors?', 'Можно снять и стирать чехол? Подойдет ли он для улицы?'), tr(lang, 'These features are not established by the reference photos. Ask for the selected fabric composition, care instructions and cover construction. This catalog presents indoor seating references and does not claim waterproofing or outdoor suitability.', 'По фото эти свойства не подтверждаются. Запросите состав ткани, рекомендации по уходу и конструкцию чехла. В каталоге представлены варианты для помещения; водостойкость и пригодность для улицы не заявляются.')),
        (tr(lang, 'How are delivery and payment confirmed?', 'Как подтверждаются доставка и оплата?'), tr(lang, 'Include the destination country and postal code with your inquiry. The seller confirms the shipping option, charge, estimated schedule and available payment method for that order. This page is an inquiry catalog, not a live payment checkout.', 'Укажите страну и почтовый индекс в запросе. Продавец подтвердит способ и стоимость доставки, ориентировочные сроки и доступную оплату для заказа. Эта страница предназначена для запроса расчета; онлайн-оплата здесь не подключена.')),
    ]
    return '<section class="wy-cushion-section"><div class="shell"><h2>' + tr(lang, 'Window seat cushion questions', 'Вопросы о подушках для подоконника') + '</h2>' + ''.join(f'<article class="wy-question"><h3>{q}</h3><p>{a}</p></article>' for q, a in qa) + '</div></section>'


def build_product(product, lang):
    p = product[lang]
    path = product_path(product, lang)
    items = [(tr(lang, '/', '/ru/'), tr(lang, 'Home', 'Главная')), (tr(lang, '/products/', '/ru/products/'), tr(lang, 'Products', 'Товары')), (category_path(lang), tr(lang, 'Window seat cushions', 'Подушки на подоконник')), (path, p['name'])]
    specs = [
        (tr(lang, 'Catalog reference', 'Код каталога'), product['reference']),
        (tr(lang, 'Reference appearance', 'Внешний вид на фото'), p['appearance']),
        (tr(lang, 'Size', 'Размер'), tr(lang, 'Made to fit; standard-size requests checked individually', 'По вашим размерам; стандартный размер уточняется')),
        (tr(lang, 'Thickness & foam', 'Толщина и наполнитель'), tr(lang, 'Confirmed with your measurements and quote', 'Согласовываются по размерам и запросу')),
        (tr(lang, 'Color', 'Цвет'), p['color']),
        (tr(lang, 'Fabric composition & care', 'Состав ткани и уход'), tr(lang, 'Confirmed for the selected fabric before ordering', 'Подтверждаются для выбранной ткани до заказа')),
    ]
    product_schema = {'@type': 'Product', '@id': ORIGIN + path + '#product', 'url': ORIGIN + path, 'name': p['name'], 'description': p['description'], 'productID': product['reference'], 'image': [ORIGIN + '/assets/cushions/' + a + '-1200.webp' for a in product['photos'] if a != 'teddy-window-scene'], 'brand': {'@type': 'Brand', 'name': 'Weieryang'}, 'category': tr(lang, 'Window seat cushions', 'Подушки на подоконник'), 'additionalProperty': [{'@type': 'PropertyValue', 'name': a, 'value': b} for a, b in specs]}
    structured = {'@context': 'https://schema.org', '@graph': [breadcrumb_schema(items), product_schema]}
    content = head(lang, path, p['name'] + ' | Weieryang', p['description'], product['style'], structured, product_path(product, 'en'), product_path(product, 'ru'), True)
    content += header(lang, product_path(product, tr(lang, 'ru', 'en')), path)
    content += f'''<main id="main-content"><section class="wy-cushion-hero"><div class="shell">{breadcrumb(items, lang)}<div class="product-hero-grid"><div><p class="eyebrow">{tr(lang, 'Window seat cushion collection', 'Коллекция подушек для подоконника')} · {product['reference']}</p><h1>{esc(p['name'])}</h1><p class="product-intro">{esc(p['description'])}</p><p class="wy-status">{tr(lang, 'Custom size · Indoor seating reference · Quote required', 'Индивидуальный размер · Для помещения · Цена по запросу')}</p><div class="product-actions"><a class="button button-dark" href="#quote">{tr(lang, 'Request my quote', 'Запросить расчет')}</a><a class="button button-light" href="#measure">{tr(lang, 'How to measure', 'Как снять размеры')}</a></div><p class="wy-photo-caption">{tr(lang, 'Photo design reference. Final size, fabric, color and included accessories are agreed before ordering.', 'Фото — ориентир дизайна. Итоговые размеры, ткань, цвет и комплектация согласовываются до заказа.')}</p></div><figure class="wy-product-image">{photo(product['style'], p['alt'], True)}<figcaption class="wy-photo-caption">{tr(lang, 'Owner-supplied design reference', 'Фото дизайна, предоставленное продавцом')} · {product['reference']}</figcaption></figure></div></div></section>
<section class="wy-cushion-section"><div class="shell"><p class="eyebrow">{tr(lang, 'Design & specification', 'Дизайн и параметры')}</p><h2>{esc(p['detail_title'])}</h2><p>{esc(p['detail'])}</p><dl class="wy-specs">{''.join(f'<div><dt>{esc(a)}</dt><dd>{esc(b)}</dd></div>' for a, b in specs)}</dl><p>{esc(p['check'])}</p></div></section>'''
    if len(product['photos']) > 1:
        figures = []
        for asset in product['photos']:
            enhanced = asset == 'teddy-window-scene'
            caption = tr(lang, 'AI-enhanced room scene for visual inspiration; use the original reference to confirm product details.', 'Сцена интерьера с обработкой ИИ для визуального ориентира; детали товара уточняйте по исходному фото.') if enhanced else tr(lang, 'Grey corduroy design reference' if asset == 'corduroy-grey' else 'Original design reference', 'Серый вельветовый вариант' if asset == 'corduroy-grey' else 'Исходное фото дизайна')
            alt = tr(lang, 'Grey ribbed corduroy-style window seat cushion' if asset == 'corduroy-grey' else 'AI-enhanced cream teddy cushion window nook' if enhanced else p['alt'], 'Серый вариант подушки с вельветовой фактурой' if asset == 'corduroy-grey' else 'Кремовая подушка тедди у окна, сцена с обработкой ИИ' if enhanced else p['alt'])
            figures.append(f'<figure>{photo(asset, alt)}<figcaption class="wy-photo-caption">{caption}</figcaption></figure>')
        content += f'<section class="wy-cushion-section wy-tinted"><div class="shell"><h2>{tr(lang, "Compare the photo references", "Сравните варианты на фото")}</h2><div class="wy-photo-grid">' + ''.join(figures) + '</div></div></section>'
    content += measurement(lang) + questions(lang, product) + quote_section(lang, product)
    content += f'<section class="wy-cushion-section"><div class="shell"><h2>{tr(lang, "Explore other cushion designs", "Другие варианты подушек")}</h2><div class="wy-related-grid">' + ''.join(card(other, lang) for other in PRODUCTS if other != product) + '</div></div></section>'
    write(path.strip('/') + '/index.html', content + footer(lang))


def build_category(lang):
    path = category_path(lang)
    title = tr(lang, 'Custom Window Seat & Bay Window Cushions | Weieryang', 'Подушки на подоконник и для эркера на заказ | Weieryang')
    name = tr(lang, 'Custom window seat cushions', 'Подушки на подоконник на заказ')
    desc = tr(lang, 'Compare four window seat cushion designs: teddy fleece, corduroy, cotton-linen style and textured woven. Send your dimensions and request a confirmed quote.', 'Четыре варианта подушек для подоконника: тедди, вельвет, фактура хлопка и льна и фактурное плетение. Пришлите размеры для подтвержденного расчета.')
    items = [(tr(lang, '/', '/ru/'), tr(lang, 'Home', 'Главная')), (tr(lang, '/products/', '/ru/products/'), tr(lang, 'Products', 'Товары')), (path, name)]
    listing = {'@type': 'ItemList', 'numberOfItems': len(PRODUCTS), 'itemListElement': [{'@type': 'ListItem', 'position': i + 1, 'url': ORIGIN + product_path(p, lang), 'name': p[lang]['name']} for i, p in enumerate(PRODUCTS)]}
    structured = {'@context': 'https://schema.org', '@graph': [breadcrumb_schema(items), {'@type': 'CollectionPage', '@id': ORIGIN + path, 'url': ORIGIN + path, 'name': name, 'description': desc, 'inLanguage': lang, 'mainEntity': listing}]}
    content = head(lang, path, title, desc, 'teddy-channel-detail', structured, category_path('en'), category_path('ru')) + header(lang, category_path(tr(lang, 'ru', 'en')))
    content += f'''<main id="main-content"><section class="wy-cushion-hero"><div class="shell">{breadcrumb(items, lang)}<div class="product-hero-grid"><div><p class="eyebrow">{tr(lang, 'Window seat & bench cushion collection', 'Коллекция для подоконников и скамей')}</p><h1>{name}</h1><p class="product-intro">{tr(lang, 'Turn the seat by your window into a place to pause. Compare four reference designs, then send the measurements of your window seat, bay window or indoor bench for a cushion quotation tailored to your space.', 'Сделайте место у окна удобным уголком для отдыха. Сравните четыре варианта дизайна и пришлите размеры подоконника, эркера или скамьи для расчета подушки под ваше пространство.')}</p><div class="product-actions"><a class="button button-dark" href="#designs">{tr(lang, 'Choose a cushion design', 'Выбрать дизайн')}</a><a class="button button-light" href="#measure">{tr(lang, 'Measure your seat', 'Снять размеры')}</a></div><p class="wy-status">{tr(lang, '4 design families · Custom and standard-size inquiries · Price confirmed by quote', '4 варианта дизайна · Стандартные и индивидуальные размеры по запросу · Цена после расчета')}</p></div><figure class="wy-product-image">{photo('teddy-channel-detail', PRODUCTS[0][lang]['alt'], True)}<figcaption class="wy-photo-caption">{tr(lang, 'Teddy fleece design reference · WY-WC01', 'Вариант тедди · WY-WC01')}</figcaption></figure></div></div></section>
<section class="wy-cushion-section" id="designs"><div class="shell"><p class="eyebrow">{tr(lang, 'Choose the look', 'Выберите внешний вид')}</p><h2>{tr(lang, 'Four designs for your indoor window seat', 'Четыре дизайна для сиденья у окна')}</h2><p>{tr(lang, 'Start with a fabric appearance and color reference. Each product page explains the design and the details to confirm for your own cushion. Photos do not establish standard dimensions, foam density or fabric composition.', 'Начните с фактуры и цветового ориентира. В каждой карточке описаны дизайн и параметры для согласования. Фото не подтверждают стандартный размер, плотность наполнителя или состав ткани.')}</p><div class="catalog-grid">{''.join(card(p, lang) for p in PRODUCTS)}</div></div></section>'''
    rows = ''.join(f'<tr><th scope="row"><a href="{product_path(p, lang)}">{esc(p[lang]["short"])}</a></th><td>{esc(p[lang]["appearance"])}</td><td>{esc(p[lang]["check"])}</td></tr>' for p in PRODUCTS)
    content += f'<section class="wy-cushion-section wy-tinted"><div class="shell"><h2>{tr(lang, "Compare the window seat cushion designs", "Сравните дизайны подушек")}</h2><div class="wy-comparison"><table><thead><tr><th scope="col">{tr(lang, "Design", "Дизайн")}</th><th scope="col">{tr(lang, "Reference appearance", "Внешний вид")}</th><th scope="col">{tr(lang, "Confirm for your order", "Что уточнить")}</th></tr></thead><tbody>{rows}</tbody></table></div></div></section>'
    content += measurement(lang) + questions(lang) + quote_section(lang)
    write(path.strip('/') + '/index.html', content + footer(lang))


def build_ru_products():
    path = '/ru/products/'
    desc = 'Каталог Weieryang: диваны и кресла для оптовых проектов, а также четыре дизайна подушек на подоконник с расчетом по вашим размерам.'
    structured = {'@context': 'https://schema.org', '@type': 'CollectionPage', 'url': ORIGIN + path, 'name': 'Каталог диванов и подушек Weieryang', 'description': desc, 'inLanguage': 'ru'}
    content = head('ru', path, 'Диваны и подушки на подоконник | Каталог Weieryang', desc, 'corduroy-ivory', structured, '/products/', path) + header('ru', '/products/', path)
    content += '''<main id="main-content"><section class="catalog-hero"><div class="shell"><p class="eyebrow">Каталог Weieryang</p><h1>Диваны и подушки для вашего проекта.</h1><p>Выберите направление: мебель для оптовой поставки или подушка для подоконника по нужным размерам. Существующие страницы диванов и упаковочные данные доступны по прежним адресам.</p><div class="wy-catalog-groups"><a class="wy-catalog-group" href="/ru/compressed-sofa/"><strong>Диваны и сиденья</strong><span>Оптовые модели, OEM и данные упаковки →</span></a><a class="wy-catalog-group" href="/ru/window-seat-cushions/"><strong>Подушки на подоконник</strong><span>4 варианта дизайна · размер и цена по запросу →</span></a></div></div></section><section class="wy-cushion-section"><div class="shell"><h2>Диваны: стартовые модели</h2><div class="catalog-grid">'''
    for slug, name, img in [('fn-011b-compressed-sofa', 'FN-011B · Сжатый диван', 'FN-011B'), ('fn-104-sofa-bed', 'FN-104 · Диван-кровать', 'FN-104'), ('fn-802-floor-sofa', 'FN-802 · Напольный диван', 'FN-802')]:
        content += f'<article class="catalog-card"><a href="/ru/products/{slug}/"><div class="catalog-image"><img src="/assets/images/{img}.webp" alt="{name}" width="900" height="700" loading="lazy"></div><div class="catalog-card-copy"><h3>{name}</h3><p>Размеры, упаковка и запрос оптовой цены →</p></div></a></article>'
    content += '</div><p><a class="button button-light" href="/products/">Все семейства диванов и кресел (EN)</a></p></div></section><section class="wy-cushion-section wy-tinted"><div class="shell"><h2>Подушки на подоконник: четыре дизайна</h2><div class="catalog-grid">' + ''.join(card(p, 'ru') for p in PRODUCTS) + '</div></div></section>'
    write('ru/products/index.html', content + quote_section('ru') + footer('ru'))


def integrate_catalog():
    path = 'products/index.html'
    content = read(path)
    newline = '\r\n' if '\r\n' in content else '\n'
    # Preserve the existing catalog's established search metadata. Cushion keywords
    # belong on the dedicated collection and product pages linked from this catalog.
    content = content.replace('Sofa Families & Custom Window Seat Cushions | Weieryang', 'Sofa Product Families and Seat Configurations | Weieryang Factory')
    content = content.replace('Browse 23 sofa and chair families with 41 configurations, plus 4 custom window seat cushion designs. Compare specifications and request a factory quotation.', 'Browse 23 Weieryang sofa and chair families with 41 seat, size and layout configurations. Compare packing data and open linked buyer guides before sending an RFQ.')
    content = content.replace('Factory-direct sofa families and custom window seat cushions. Compare sofa packing data or choose a cushion design and request a made-to-fit quotation.', 'Factory-direct upholstered furniture families organized by seat count, size and layout configuration, with buyer guides for RFQ, samples and packing.')
    if '/assets/cushion-catalog.css' not in content:
        content = content.replace('</head>', '<link rel="stylesheet" href="/assets/cushion-catalog.css?v=20261006a">' + newline + alternates('/products/', '/ru/products/').replace('\n', newline) + newline + '</head>')
    content = content.replace('<strong>23</strong><span>product families</span>', '<strong>27</strong><span>23 sofa + 4 cushion families</span>')
    content = content.replace('<strong>41</strong><span>available configurations</span>', '<strong>41</strong><span>sofa configurations</span>')
    content = content.replace('<strong>6</strong><span>product categories</span>', '<strong>2</strong><span>main product groups</span>')
    content = content.replace('<strong data-product-count>23 families</strong>', '<strong data-product-count>27 families</strong>')
    content = content.replace('Every original model remains available inside its product family', 'Sofa configurations and cushion designs are organized in separate groups')
    if '<!-- cushion-catalog-groups:start -->' not in content:
        groups = '<!-- cushion-catalog-groups:start --><div class="shell wy-catalog-groups"><a class="wy-catalog-group" href="/products/?group=sofas#sofas-seating"><strong>Sofas &amp; seating</strong><span>23 families · 41 configurations · all six existing sofa / seating categories</span></a><a class="wy-catalog-group" href="/window-seat-cushions/"><strong>Window seat cushions</strong><span>4 designs · custom dimensions · individual quotations →</span></a></div><!-- cushion-catalog-groups:end -->'
        content = content.replace('  <section class="catalog-section">', groups + newline + '  <section class="catalog-section">', 1)
    if 'data-product-filter="window-seat-cushions"' not in content:
        filter_button = '          <button class="filter-button" id="window-seat-cushions" type="button" data-product-filter="window-seat-cushions" aria-pressed="false">Window Seat Cushions &middot; 4</button>'
        needle = '        </div>' + newline + '        <div class="catalog-search">'
        assert needle in content
        content = content.replace(needle, filter_button + newline + needle, 1)
    if 'data-product-filter="sofas-seating"' not in content:
        needle = '<button class="filter-button" type="button" data-product-filter="all" aria-pressed="true">All families</button>'
        content = content.replace(needle, needle + newline + '          <button class="filter-button" id="sofas-seating" type="button" data-product-filter="sofas-seating" aria-pressed="false">Sofas &amp; Seating &middot; 23</button>')
    content = re.sub(r'(data-category=")([^"\n]*)(")', lambda m: m.group(0) if 'window-seat-cushions' in m.group(2) or 'sofas-seating' in m.group(2) else m.group(1) + m.group(2) + ' sofas-seating' + m.group(3), content)
    content = re.sub(r'<!-- cushion-catalog-cards:start -->.*?<!-- cushion-catalog-cards:end -->\r?\n', '', content, flags=re.S)
    needle = '      </div>' + newline + '    </div>' + newline + '  </section>' + newline + '  <section class="product-section product-section-dark"'
    assert needle in content
    cards = '<!-- cushion-catalog-cards:start -->' + newline + newline.join(card(p, 'en').replace('\n', newline) for p in PRODUCTS) + newline + '<!-- cushion-catalog-cards:end -->' + newline
    content = content.replace(needle, cards + needle, 1)
    pattern = r'<script type="application/ld\+json">(.*?)</script>'
    match = re.search(pattern, content, flags=re.S)
    listing = json.loads(match.group(1))
    listing['itemListElement'] = [item for item in listing['itemListElement'] if not any(p['slug'] in item['url'] for p in PRODUCTS)]
    listing['itemListElement'] += [{'@type': 'ListItem', 'position': 24 + i, 'url': ORIGIN + product_path(p, 'en'), 'name': p['en']['name']} for i, p in enumerate(PRODUCTS)]
    listing['numberOfItems'] = 27
    listing['name'] = 'Weieryang Sofa and Window Seat Cushion Product Families'
    content = content[:match.start()] + schema(listing) + content[match.end():]
    if '<a href="/window-seat-cushions/">Window seat cushions</a>' not in content:
        content = content.replace('<a href="/products/#lounge-chair">Lounge chairs</a>', '<a href="/products/#lounge-chair">Lounge chairs</a>' + newline + '      <a href="/window-seat-cushions/">Window seat cushions</a>')
    write(path, content)


def integrate_home_and_discovery():
    for path, old, new in [('index.html', PREVIEW + '/?entry=header-home-en', '/window-seat-cushions/?entry=header-home-en'), ('ru/index.html', PREVIEW + '/ru/?entry=header-home-ru', '/ru/window-seat-cushions/?entry=header-home-ru')]:
        content = read(path)
        assert old in content or new in content
        write(path, content.replace(old, new))
    urls = [ORIGIN + category_path(lang) for lang in ['en', 'ru']] + [ORIGIN + '/ru/products/'] + [ORIGIN + product_path(p, lang) for p in PRODUCTS for lang in ['en', 'ru']]
    changed = [ORIGIN + '/', ORIGIN + '/ru/', ORIGIN + '/products/']
    sitemap = read('sitemap.xml')
    for url in urls:
        if '<loc>' + url + '</loc>' not in sitemap:
            entry = f'  <url><loc>{url}</loc><lastmod>{DATA["updated"]}</lastmod><changefreq>monthly</changefreq><priority>0.70</priority></url>\n'
            sitemap = sitemap.replace('</urlset>', entry + '</urlset>')
    for url in changed + urls:
        pattern = r'(<loc>' + re.escape(url) + r'</loc><lastmod>)[^<]+(</lastmod>)'
        sitemap = re.sub(pattern, lambda m: m.group(1) + DATA['updated'] + m.group(2), sitemap)
    write('sitemap.xml', sitemap)
    llms = read('llms.txt')
    if '\n## Window Seat Cushion Collection\n' in llms:
        llms = llms.split('\n## Window Seat Cushion Collection\n')[0].rstrip() + '\n'
    llms = llms.rstrip() + '\n'
    llms += '\n## Window Seat Cushion Collection\n'
    llms += 'Weieryang also has a separate quote-based indoor window seat and bench cushion collection. The sofa catalog and its packing specifications remain separate. Four photo-reference design families are available for inquiry; finished size, foam, fabric composition, color, accessories, shipping, production time and payment terms require quotation confirmation. There are no confirmed online prices or stock assertions for these photo designs.\n'
    llms += f'- English collection: {ORIGIN}/window-seat-cushions/\n- Russian collection: {ORIGIN}/ru/window-seat-cushions/\n- Russian product catalog: {ORIGIN}/ru/products/\n'
    for p in PRODUCTS:
        llms += f'- {p["reference"]} {p["en"]["name"]}: {ORIGIN}{product_path(p, "en")}\n'
        llms += f'- {p["reference"]} {p["ru"]["name"]}: {ORIGIN}{product_path(p, "ru")}\n'
    llms += 'For a cushion quotation, provide the catalog reference, preferred photo, all seating-area dimensions, finished thickness, front drop if requested, quantity, destination country and postal code. Cotton-linen style describes appearance, not a certified fiber composition. AI-enhanced scenes are labeled and excluded from the Product schema image list.\n'
    write('llms.txt', llms)


if __name__ == '__main__':
    for language in ['en', 'ru']:
        build_category(language)
        for product in PRODUCTS:
            build_product(product, language)
    build_ru_products()
    integrate_catalog()
    integrate_home_and_discovery()
    print('Built 4 cushion designs × 2 languages, 2 collection pages and 1 Russian catalog; preserved original sofa details.')
