#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build static, bilingual cushion pages. No framework or checkout migration.

Run from any directory with Python 3. Rebuilding is idempotent. The owner-supplied
photo derivatives live in assets/cushions; data/cushions.json is the catalog source.
Legacy sofa details and original catalog cards are never regenerated by this script.
"""
import html
import json
import re
from pathlib import Path
from urllib.parse import urlencode

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'data/cushions.json').read_text())
PRODUCTS = DATA['products']
GUIDE_DATA = json.loads((ROOT / 'data/cushion-guides.json').read_text())
GUIDES = GUIDE_DATA['guides']
ORIGIN = 'https://weieryang.com'
PREVIEW = 'https://weieryang-cushions.yhsj98251.chatgpt.site'
CHANGED_HTML = set()


def esc(value):
    return html.escape(str(value), quote=True)


def read(path):
    return (ROOT / path).read_bytes().decode('utf-8')


def write(path, content):
    dest = ROOT / path
    dest.parent.mkdir(parents=True, exist_ok=True)
    encoded = content.encode('utf-8')
    if dest.exists() and dest.read_bytes() == encoded:
        return
    dest.write_bytes(encoded)
    if dest.suffix == '.html':
        CHANGED_HTML.add(path)


def tr(lang, en, ru):
    return ru if lang == 'ru' else en


def category_path(lang):
    return ('/ru' if lang == 'ru' else '') + '/window-seat-cushions/'


def product_path(product, lang):
    return ('/ru' if lang == 'ru' else '') + '/products/' + product['slug'] + '/'


def guide_path(guide, lang):
    return category_path(lang) + guide['slug'] + '/'


def photo(asset, alt, hero=False, layout='catalog'):
    source = '/assets/cushions/' + asset
    # Match the existing shell and grid breakpoints; lazy images can use their
    # laid-out width with explicit fallbacks for browsers without sizes=auto.
    sizes = {
        'hero': '(max-width: 620px) calc(100vw - 28px), (max-width: 796px) calc(100vw - 36px), (max-width: 900px) 760px, (max-width: 960px) calc(55vw - 41.8px), (max-width: 1060px) calc(55vw - 52.8px), (max-width: 1288px) calc(60vw - 57.6px), 715.2px',
        'catalog': 'auto, (max-width: 620px) calc(100vw - 28px), (max-width: 796px) calc(50vw - 29px), (max-width: 900px) 369px, (max-width: 1060px) calc(50vw - 35px), (max-width: 1288px) calc(33.3333vw - 30.6667px), 398.67px',
        'related': 'auto, (max-width: 620px) calc(100vw - 28px), (max-width: 680px) calc(100vw - 36px), (max-width: 796px) calc(50vw - 30px), (max-width: 900px) 368px, (max-width: 960px) calc(50vw - 36px), (max-width: 1288px) calc(33.3333vw - 32px), 397.33px',
        'gallery': 'auto, (max-width: 620px) calc(100vw - 28px), (max-width: 680px) calc(100vw - 36px), (max-width: 796px) calc(50vw - 30px), (max-width: 900px) 368px, (max-width: 1288px) calc(50vw - 36px), 608px',
    }['hero' if hero else layout]
    return (f'<img src="{source}-800.webp" srcset="{source}-400.webp 400w, {source}-800.webp 800w, {source}-1200.webp 1200w" '
            f'sizes="{sizes}" '
            f'alt="{esc(alt)}" width="1200" height="1200" decoding="async" '
            + ('fetchpriority="high" loading="eager"' if hero else 'loading="lazy"') + '>')


def schema(data):
    return '<script type="application/ld+json">' + json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/') + '</script>'


def alternates(en, ru):
    return '\n'.join(f'<link rel="alternate" hreflang="{lang}" href="{ORIGIN}{path}">' for lang, path in [('en', en), ('ru', ru), ('x-default', en)])


def head(lang, path, title, description, image, structured, en, ru, product=False):
    return f'''<!doctype html>
<html lang="{lang}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<meta name="robots" content="index, follow, max-image-preview:large">
<link rel="canonical" href="{ORIGIN}{path}">
{alternates(en, ru)}
<meta property="og:site_name" content="Weieryang"><meta property="og:type" content="{'product' if product else 'website'}">
<meta property="og:locale" content="{'ru_RU' if lang == 'ru' else 'en_US'}">
<meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{ORIGIN}{path}"><meta property="og:image" content="{ORIGIN}/assets/cushions/{image}-1200.webp">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{esc(title)}">
<meta name="twitter:description" content="{esc(description)}"><meta name="twitter:image" content="{ORIGIN}/assets/cushions/{image}-1200.webp">
{schema(structured)}
<link rel="icon" type="image/png" href="/assets/images/weieryang-favicon-32.png">
<link rel="stylesheet" href="/assets/factory-site.css?v=20260613d">
<link rel="stylesheet" href="/assets/product-system.css?v=20260613d">
<link rel="stylesheet" href="/assets/en-editorial.css?v=20260917a">
<link rel="stylesheet" href="/assets/cushion-catalog.css?v=20261007b">
<script defer src="/assets/factory-site.js?v=20261004a"></script>
<script defer src="/assets/site-analytics.js?v=20261007a"></script>
<script defer src="/assets/cushion-inquiry.js?v=20261007b"></script>
</head><body lang="{lang}" class="factory-v2 product-page editorial-en wy-cushion-page">
<a class="skip-link" href="#main-content">{tr(lang, 'Skip to content', 'К содержанию')}</a>'''


def header(lang, other, current=None):
    home = '/ru/' if lang == 'ru' else '/'
    products = '/ru/products/' if lang == 'ru' else '/products/'
    current = current or category_path(lang)
    products_current = ' aria-current="page"' if current == products else ''
    category_current = ' aria-current="page"' if current == category_path(lang) else ''
    return f'''<div class="topbar inner-topbar"><div class="shell topbar-inner"><span>{tr(lang, 'Weieryang · Sofas & custom window seat cushions', 'Weieryang · Диваны и подушки для подоконника')}</span><a href="mailto:tangkelian@weieryang.com">tangkelian@weieryang.com</a></div></div>
<header class="site-header inner-header"><div class="shell header-inner">
<a class="brand" href="{home}" aria-label="{tr(lang, 'Weieryang homepage', 'Главная Weieryang')}"><span class="brand-mark"><img src="/assets/images/weieryang-brand-logo-180.webp" alt="" width="72" height="54"></span><span class="brand-copy"><strong>Weieryang</strong><small>{tr(lang, 'Sofas & custom cushions', 'Диваны и подушки')}</small></span></a>
<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav" aria-label="{tr(lang, 'Open menu', 'Открыть меню')}"><span></span><span></span><span></span></button>
<nav class="main-nav" id="main-nav" aria-label="{tr(lang, 'Primary navigation', 'Основная навигация')}"><a href="{home}">{tr(lang, 'Factory', 'Главная')}</a><a href="{products}"{products_current}>{tr(lang, 'All products', 'Все товары')}</a><a href="{category_path(lang)}"{category_current}>{tr(lang, 'Window Seat Cushions', 'Подушки на подоконник')}</a><a class="text-link" href="{other}" lang="{tr(lang, 'ru', 'en')}" hreflang="{tr(lang, 'ru', 'en')}">{tr(lang, 'RU', 'EN')}</a></nav>
<div class="header-actions"><a class="button button-dark button-small" href="#quote">{tr(lang, 'Request a quote', 'Запросить цену')}</a></div>
</div></header>'''


def footer(lang):
    return f'''</main><footer class="wy-footer"><div class="shell"><div><strong>Weieryang</strong><p>Wuhan, China · © <span id="year">2026</span></p></div><nav aria-label="{tr(lang, 'Footer navigation', 'Навигация внизу страницы')}"><a href="{tr(lang, '/products/', '/ru/products/')}">{tr(lang, 'All products', 'Все товары')}</a><a href="{category_path(lang)}">{tr(lang, 'Window seat cushions', 'Подушки на подоконник')}</a><a href="{tr(lang, '/contact/', '/ru/contact/')}">{tr(lang, 'Contact', 'Контакты')}</a><a href="mailto:tangkelian@weieryang.com">Email</a></nav></div></footer></body></html>'''


def breadcrumb(items, lang):
    body = '<span aria-hidden="true">/</span>'.join(f'<a href="{path}">{esc(label)}</a>' if i < len(items) - 1 else f'<span aria-current="page">{esc(label)}</span>' for i, (path, label) in enumerate(items))
    return f'<nav class="breadcrumb" aria-label="{tr(lang, "Breadcrumb", "Навигационная цепочка")}">{body}</nav>'


def breadcrumb_schema(items):
    return {'@type': 'BreadcrumbList', 'itemListElement': [{'@type': 'ListItem', 'position': i + 1, 'name': label, 'item': ORIGIN + path} for i, (path, label) in enumerate(items)]}


def preview_url(product, lang):
    build = {'mode': 'custom', 'unit': tr(lang, 'in', 'cm'), 'market': tr(lang, 'US', 'RU'), 'length': None, 'width': None, 'thickness': None, 'stylePreference': product['style']}
    params = {'entry': 'catalog-' + product['reference'].lower(), 'configuration': json.dumps({'version': 1, 'build': build, 'drafts': {}}, separators=(',', ':'))}
    return PREVIEW + tr(lang, '/', '/ru/') + '?' + urlencode(params)


def quote_section(lang, product=None):
    name = product[lang]['name'] if product else tr(lang, 'Window seat cushion', 'Подушка на подоконник')
    ref = product['reference'] if product else ''
    body = tr(lang, f'Hello Weieryang, please quote {name} {ref}.\nLength:\nWidth / depth:\nFinished thickness:\nFront drop, if needed:\nPreferred photo / color:\nQuantity:\nDestination country and postal code:\nPlease confirm fabric, foam, item price, shipping and production time.', f'Здравствуйте! Прошу рассчитать {name} {ref}.\nДлина:\nШирина / глубина:\nТолщина сиденья:\nВысота свисающего края, если нужен:\nФото / цвет:\nКоличество:\nСтрана и почтовый индекс:\nПрошу подтвердить ткань, наполнитель, цену, доставку и срок изготовления.')
    email = 'mailto:tangkelian@weieryang.com?' + urlencode({'subject': f'{name} {ref} — quote request', 'body': body}).replace('+', '%20')
    whatsapp = 'https://wa.me/8613317178019?' + urlencode({'text': body})
    preview = f'<p data-inquiry-preview-fallback><a href="{esc(preview_url(product, lang))}">{tr(lang, "Open customization preview with this design", "Открыть настройку с выбранным дизайном")} →</a></p>' if product else ''
    options = f'<option value="recommend">{tr(lang, "Help me choose a design", "Помогите выбрать дизайн")}</option>' + ''.join(f'<option value="{p["reference"]}" data-name="{esc(p[lang]["name"])}" data-image="/assets/cushions/{p["style"]}-400.webp" data-image-alt="{esc(p[lang]["alt"])}" data-preview-url="{esc(preview_url(p, lang))}"{" selected" if p == product else ""}>{p["reference"]} · {esc(p[lang]["short"])}</option>' for p in PRODUCTS)
    form = f'''<form data-cushion-inquiry hidden>
<label for="cushion-design">{tr(lang, '1. Design reference', '1. Дизайн')}<select id="cushion-design" name="design">{options}</select></label>
<div class="wy-inquiry-selection" data-inquiry-selection hidden><img data-inquiry-design-image alt="" width="120" height="120" loading="lazy" decoding="async"><p><a data-inquiry-preview>{tr(lang, 'Open customization preview with the selected design', 'Открыть настройку выбранного дизайна')} →</a><small>{tr(lang, 'Photo reference; final fabric and specification require confirmation.', 'Фото — ориентир; ткань и параметры требуют согласования.')}</small></p></div>
<label for="cushion-dimensions">{tr(lang, '2. Dimensions & unit', '2. Размеры и единицы')}<input id="cushion-dimensions" name="dimensions" required maxlength="250" placeholder="{tr(lang, 'Length × depth × thickness; inches or cm', 'Длина × глубина × толщина; см или дюймы')}" aria-describedby="dimension-help"></label>
<p class="wy-field-help" id="dimension-help">{tr(lang, 'For an angled seat, list all edges and attach a sketch in your email or chat.', 'Для сложной формы укажите все стороны и приложите эскиз к письму или сообщению.')}</p>
<label for="cushion-quantity">{tr(lang, '3. Quantity', '3. Количество')}<input id="cushion-quantity" name="quantity" type="number" min="1" max="9999" step="1" value="1" required inputmode="numeric"></label>
<label for="cushion-destination">{tr(lang, '4. Delivery country & postal code', '4. Страна и почтовый индекс')}<input id="cushion-destination" name="destination" required maxlength="160" placeholder="{tr(lang, 'e.g. United States, 10001', 'Например, Россия, 101000')}" autocomplete="off"></label>
<label for="cushion-preferences">{tr(lang, '5. Color, front drop & other preferences (optional)', '5. Цвет, свисающий край и другие пожелания (необязательно)')}<textarea id="cushion-preferences" name="preferences" rows="3" maxlength="600"></textarea></label>
<button class="button button-dark" type="submit">{tr(lang, 'Prepare my inquiry', 'Подготовить запрос')}</button>
<p class="wy-photo-caption">{tr(lang, 'Your entries stay in this page until you choose email or WhatsApp. No message is sent by this form.', 'Введенные данные остаются на странице до выбора email или WhatsApp. Форма сама не отправляет сообщение.')}</p>
<div class="wy-inquiry-result" data-inquiry-result hidden><h4 tabindex="-1" data-inquiry-heading>{tr(lang, 'Review, then send your message', 'Проверьте и отправьте сообщение')}</h4><pre data-inquiry-message></pre><div class="product-actions"><button class="button button-dark" type="button" data-inquiry-email>{tr(lang, 'Open email to send', 'Открыть email для отправки')}</button><button class="button button-light" type="button" data-inquiry-whatsapp>WhatsApp</button><button class="button button-light" data-inquiry-copy type="button">{tr(lang, 'Copy message', 'Скопировать текст')}</button><button class="button button-light" data-inquiry-edit type="button">{tr(lang, 'Edit requirements', 'Изменить данные')}</button></div><p class="wy-photo-caption">{tr(lang, 'The inquiry is complete only after you send it in your email app or WhatsApp. Add photos or your sketch there.', 'Запрос будет отправлен только после отправки в вашей почте или WhatsApp. Там же добавьте фото или эскиз.')}</p><p role="status" data-inquiry-status></p></div>
</form>'''
    return f'''<section class="wy-cushion-section wy-tinted"><div class="shell wy-cushion-grid"><div><p class="eyebrow">{tr(lang, 'Your measurements, your quote', 'Ваши размеры — ваш расчет')}</p><h2>{tr(lang, 'Tell us about your window seat.', 'Расскажите о вашем сиденье у окна.')}</h2><p>{tr(lang, 'Send the design reference, length, seat depth, finished thickness, quantity and delivery country / postal code. For an angled seat, add a dimensioned sketch. Your quote will confirm the cushion specification, item price, shipping charge and production time before payment.', 'Укажите дизайн, длину, глубину сиденья, толщину, количество, страну и почтовый индекс. Для сложной формы приложите эскиз с размерами. Перед оплатой в предложении подтверждаются спецификация, цена товара, стоимость доставки и срок изготовления.')}</p><ol class="wy-quote-steps"><li>{tr(lang, 'Prepare your requirements below.', 'Подготовьте требования в форме.')}</li><li>{tr(lang, 'Send the message, adding any photos or sketch.', 'Отправьте сообщение и добавьте фото или эскиз.')}</li><li>{tr(lang, 'Review the specification and complete quotation before ordering.', 'Проверьте спецификацию и полный расчет до заказа.')}</li></ol><p><a href="{tr(lang, '/contact/', '/ru/contact/')}">{tr(lang, 'Company & contact details', 'Компания и контакты')} →</a></p></div><div class="wy-quote-panel" id="quote"><h3 data-inquiry-design-heading>{esc(name)} {ref}</h3><p>{tr(lang, 'Custom sizes are quoted individually. For a standard-size request, send the size you need so availability can be checked. Shipping to the United States or Russia and the available payment method are confirmed for the destination.', 'Нестандартный размер рассчитывается индивидуально. Для стандартного размера укажите нужные параметры, чтобы проверить наличие. Возможность доставки в США или Россию и способ оплаты подтверждаются для конкретного адреса.')}</p>{form}<div data-inquiry-fallback><p>{tr(lang, 'Send your dimensions directly:', 'Отправьте размеры напрямую:')}</p><div class="product-actions"><a class="button button-dark" href="{esc(email)}">{tr(lang, 'Prepare email inquiry', 'Подготовить запрос по email')}</a><a class="button button-light" href="{esc(whatsapp)}" target="_blank" rel="noopener noreferrer">WhatsApp</a></div></div>{preview}<p class="wy-photo-caption">{tr(lang, 'Quotation first. Photo-based designs have no confirmed online price yet.', 'Сначала расчет. Онлайн-цена вариантов по фото пока не подтверждена.')}</p></div></div></section>'''


def card(product, lang, legacy=False, layout='catalog'):
    p = product[lang]
    return f'''<article class="catalog-card family-card wy-cushion-card" data-product-card data-category="window-seat-cushions" data-search="{esc((product['reference'] + ' ' + p['name'] + ' custom bay window bench cushion ' + p['appearance']).lower())}">
<a href="{product_path(product, lang)}"><div class="catalog-image">{photo(product['style'], p['alt'], layout=layout)}<span class="catalog-category">{tr(lang, 'Window seat cushion', 'Подушка на подоконник')}</span></div><div class="catalog-card-copy"><div class="catalog-card-heading"><div><h2>{esc(p['short'])}</h2><p class="catalog-card-name">{product['reference']}</p></div><span class="catalog-arrow" aria-hidden="true">↗</span></div><p class="family-description">{esc(p['description'])}</p></div></a><div class="catalog-card-copy catalog-card-actions"><a class="button button-light" href="{product_path(product, lang)}">{tr(lang, 'View design', 'Посмотреть дизайн')}</a><a class="button button-dark" href="{product_path(product, lang)}#quote">{tr(lang, 'Request a quote', 'Запросить цену')}</a></div></article>'''


def measurement(lang):
    steps = [
        (tr(lang, 'Measure the seating area', 'Измерьте сиденье'), tr(lang, 'Measure the usable length and depth on the bench, in inches or centimeters. For a bay window, record front and back widths plus angled edges; include a sketch or template.', 'Измерьте полезную длину и глубину скамьи в сантиметрах или дюймах. Для эркера укажите переднюю и заднюю ширину и наклонные стороны; добавьте эскиз или шаблон.')),
        (tr(lang, 'Separate thickness and drop', 'Разделите толщину и свисающий край'), tr(lang, 'Choose the finished cushion thickness separately from any decorative front drop. Check the height against windows, handles, drawers and the intended sitting position.', 'Толщину подушки и высоту декоративного свисающего края указывайте отдельно. Проверьте высоту относительно окна, ручек, ящиков и удобного положения сидя.')),
        (tr(lang, 'Confirm the complete quote', 'Подтвердите полный расчет'), tr(lang, 'Send your preferred photo, color, quantity and postal code. Confirm fabric, foam, price, shipping and production time before approving the order.', 'Пришлите выбранное фото, цвет, количество и почтовый индекс. До заказа подтвердите ткань, наполнитель, цену, доставку и срок изготовления.')),
    ]
    return f'<section class="wy-cushion-section" id="measure"><div class="shell"><p class="eyebrow">{tr(lang, "Sizing guide", "Как снять размеры")}</p><h2>{tr(lang, "How to measure a custom window seat cushion", "Как измерить подушку для подоконника")}</h2><ol class="wy-step-list">' + ''.join(f'<li><h3>{a}</h3><p>{b}</p></li>' for a, b in steps) + f'</ol><p><a href="{guide_path(GUIDES[0], lang)}">{tr(lang, "Read the full measurement guide with an angled-seat diagram", "Полная инструкция с эскизом для эркера")} →</a></p></div></section>'


def guide_links(lang, exclude=None):
    links = ''.join(f'<article class="wy-guide-card"><h3><a href="{guide_path(g, lang)}">{esc(g[lang].get("link_label", g[lang]["name"]))}</a></h3><p>{esc(g[lang]["description"])}</p></article>' for g in GUIDES if g != exclude)
    return f'<section class="wy-cushion-section wy-tinted"><div class="shell"><p class="eyebrow">{tr(lang, "Before you order", "Перед заказом")}</p><h2>{tr(lang, "Practical cushion buying guides", "Практические инструкции по выбору")}</h2><div class="wy-guide-grid">{links}</div></div></section>'


def measurement_diagram(lang):
    label = tr(lang, 'Angled seat: A front, B back, C depth, D left side, E right side. Diagram is not to scale.', 'Сиденье эркера: A спереди, B сзади, C глубина, D слева, E справа. Схема без масштаба.')
    return f'''<figure class="wy-measure-diagram"><svg viewBox="0 0 640 310" role="img" aria-labelledby="measure-title measure-desc"><title id="measure-title">{tr(lang, 'Top view of an angled bay window seat', 'Вид сверху на сиденье эркера')}</title><desc id="measure-desc">{label}</desc><defs><marker id="arrow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#223d2a"/></marker></defs><path d="M200 70 H440 L550 220 H90 Z" fill="#e5decd" stroke="#223d2a" stroke-width="3"/><g stroke="#223d2a" stroke-width="2" marker-start="url(#arrow)" marker-end="url(#arrow)"><path d="M95 263 H545"/><path d="M202 32 H438"/><path d="M320 78 V212"/><path d="M173 75 L73 214"/><path d="M467 75 L567 214"/></g><g fill="#223d2a" font-size="22" font-family="Arial,sans-serif" text-anchor="middle"><text x="320" y="296">A</text><text x="320" y="23">B</text><text x="344" y="153">C</text><text x="102" y="137">D</text><text x="540" y="137">E</text></g></svg><figcaption>{label}</figcaption></figure>'''


def build_guide(guide, lang):
    g = guide[lang]
    path = guide_path(guide, lang)
    items = [(tr(lang, '/', '/ru/'), tr(lang, 'Home', 'Главная')), (category_path(lang), tr(lang, 'Window seat cushions', 'Подушки на подоконник')), (path, g['name'])]
    article = {'@type': 'Article', '@id': ORIGIN + path + '#article', 'headline': g['name'], 'description': g['description'], 'inLanguage': lang, 'datePublished': guide['published'], 'dateModified': GUIDE_DATA['updated'], 'mainEntityOfPage': ORIGIN + path, 'image': ORIGIN + '/assets/cushions/' + guide['image'] + '-1200.webp', 'author': {'@type': 'Organization', 'name': 'Weieryang', 'url': ORIGIN + '/contact/'}, 'publisher': {'@type': 'Organization', 'name': 'Weieryang', 'url': ORIGIN}}
    content = head(lang, path, g['title'], g['description'], guide['image'], {'@context': 'https://schema.org', '@graph': [breadcrumb_schema(items), article]}, guide_path(guide, 'en'), guide_path(guide, 'ru')) + header(lang, guide_path(guide, tr(lang, 'ru', 'en')), path)
    content += f'<main id="main-content"><section class="wy-cushion-hero"><div class="shell">{breadcrumb(items, lang)}<div class="product-hero-grid"><div><p class="eyebrow">{tr(lang, "Cushion buying guide", "Инструкция по выбору подушки")}</p><h1>{esc(g["name"])}</h1><p class="product-intro">{esc(g["intro"])}</p><p class="wy-photo-caption">Weieryang · <time datetime="{GUIDE_DATA["updated"]}">{GUIDE_DATA["updated"]}</time></p><div class="product-actions"><a class="button button-dark" href="#quote">{tr(lang, "Prepare a cushion inquiry", "Подготовить запрос")}</a><a class="button button-light" href="{category_path(lang)}">{tr(lang, "Compare the four designs", "Сравнить четыре дизайна")}</a></div></div><figure class="wy-product-image">{photo(guide["image"], tr(lang, "Window seat cushion design reference", "Вариант дизайна подушки для подоконника"), True)}<figcaption class="wy-photo-caption">{tr(lang, "Owner-supplied design reference", "Фото дизайна, предоставленное продавцом")}</figcaption></figure></div></div></section>'
    content += '<section class="wy-cushion-section"><div class="shell wy-guide-article"><nav class="wy-guide-contents" aria-label="' + tr(lang, 'In this guide', 'Содержание') + '"><strong>' + tr(lang, 'In this guide', 'Содержание') + '</strong><ul>' + ''.join(f'<li><a href="#{s["id"]}">{esc(s["question"])}</a></li>' for s in g['sections']) + '</ul></nav>'
    for section in g['sections']:
        content += f'<section class="wy-guide-part" id="{section["id"]}"><h2>{esc(section["question"])}</h2>' + ''.join(f'<p>{esc(p)}</p>' for p in section['paragraphs'])
        if section['id'] == 'shape':
            content += measurement_diagram(lang)
        if section['id'] == 'looks':
            rows = ''.join(f'<tr><th scope="row"><a href="{product_path(p, lang)}">{p["reference"]} · {esc(p[lang]["short"])}</a></th><td>{esc(p[lang]["appearance"])}</td><td>{esc(p[lang]["check"])}</td></tr>' for p in PRODUCTS)
            content += f'<div class="wy-comparison"><table><caption>{tr(lang, "Photo designs and the details to confirm", "Дизайны по фото и параметры для согласования")}</caption><thead><tr><th scope="col">{tr(lang, "Design", "Дизайн")}</th><th scope="col">{tr(lang, "Photo appearance", "Внешний вид")}</th><th scope="col">{tr(lang, "Check before ordering", "Что уточнить")}</th></tr></thead><tbody>{rows}</tbody></table></div>'
        content += '</section>'
    content += '</div></section>' + guide_links(lang, guide) + quote_section(lang) + footer(lang)
    write(path.strip('/') + '/index.html', content)


def questions(lang, product=None):
    qa = []
    if product:
        qa.append((product[lang]['question'], product[lang]['answer']))
    qa += [
        (tr(lang, 'Can I request a standard size or a custom size?', 'Можно запросить стандартный размер или размер на заказ?'), tr(lang, 'Both can be discussed. Send your required dimensions. Standard-size stock and final custom specifications must be confirmed in the quotation; the photo is not a size or stock guarantee.', 'Можно обсудить оба варианта. Пришлите нужные размеры. Наличие стандартного размера и параметры индивидуального заказа подтверждаются в предложении; фото не гарантирует размер или наличие.')),
        (tr(lang, 'What determines the cushion price?', 'От чего зависит цена подушки?'), tr(lang, 'The quoted specification includes length, depth, thickness, shape, fabric, foam, front edge and quantity. Shipping is checked separately for the destination. A photo design is not priced by the sofa packing data or a generic cushion estimate.', 'В расчет входят длина, глубина, толщина, форма, ткань, наполнитель, передний край и количество. Доставка рассчитывается отдельно по адресу. Цена варианта по фото не определяется упаковочными данными дивана или общим калькулятором.')),
        (tr(lang, 'Is the cover removable, washable or suitable for outdoors?', 'Можно снять и стирать чехол? Подойдет ли он для улицы?'), tr(lang, 'These features are not established by the reference photos. Ask for the selected fabric composition, care instructions and cover construction. This catalog presents indoor seating references and does not claim waterproofing or outdoor suitability.', 'По фото эти свойства не подтверждаются. Запросите состав ткани, рекомендации по уходу и конструкцию чехла. В каталоге представлены варианты для помещения; водостойкость и пригодность для улицы не заявляются.')),
        (tr(lang, 'How are delivery and payment confirmed?', 'Как подтверждаются доставка и оплата?'), tr(lang, 'Include the destination country and postal code with your inquiry. The seller confirms the shipping option, charge, estimated schedule and available payment method for that order. This page is an inquiry catalog, not a live payment checkout.', 'Укажите страну и почтовый индекс в запросе. Продавец подтвердит способ и стоимость доставки, ориентировочные сроки и доступную оплату для заказа. Эта страница предназначена для запроса расчета; онлайн-оплата здесь не подключена.')),
    ]
    return '<section class="wy-cushion-section"><div class="shell"><h2>' + tr(lang, 'Window seat cushion questions', 'Вопросы о подушках для подоконника') + '</h2>' + ''.join(f'<article class="wy-question"><h3>{q}</h3><p>{a}</p></article>' for q, a in qa) + '</div></section>'


def build_product(product, lang):
    p = product[lang]
    path = product_path(product, lang)
    items = [(tr(lang, '/', '/ru/'), tr(lang, 'Home', 'Главная')), (tr(lang, '/products/', '/ru/products/'), tr(lang, 'Products', 'Товары')), (category_path(lang), tr(lang, 'Window seat cushions', 'Подушки на подоконник')), (path, p['name'])]
    specs = [
        (tr(lang, 'Catalog reference', 'Код каталога'), product['reference']),
        (tr(lang, 'Reference appearance', 'Внешний вид на фото'), p['appearance']),
        (tr(lang, 'Size', 'Размер'), tr(lang, 'Made to fit; standard-size requests checked individually', 'По вашим размерам; стандартный размер уточняется')),
        (tr(lang, 'Thickness & foam', 'Толщина и наполнитель'), tr(lang, 'Confirmed with your measurements and quote', 'Согласовываются по размерам и запросу')),
        (tr(lang, 'Color', 'Цвет'), p['color']),
        (tr(lang, 'Fabric composition & care', 'Состав ткани и уход'), tr(lang, 'Confirmed for the selected fabric before ordering', 'Подтверждаются для выбранной ткани до заказа')),
    ]
    product_schema = {'@type': 'Product', '@id': ORIGIN + path + '#product', 'url': ORIGIN + path, 'name': p['name'], 'description': p['description'], 'productID': product['reference'], 'image': [ORIGIN + '/assets/cushions/' + a + '-1200.webp' for a in product['photos'] if a != 'teddy-window-scene'], 'brand': {'@type': 'Brand', 'name': 'Weieryang'}, 'category': tr(lang, 'Window seat cushions', 'Подушки на подоконник'), 'additionalProperty': [{'@type': 'PropertyValue', 'name': a, 'value': b} for a, b in specs]}
    structured = {'@context': 'https://schema.org', '@graph': [breadcrumb_schema(items), product_schema]}
    content = head(lang, path, p['name'] + ' | Weieryang', p['description'], product['style'], structured, product_path(product, 'en'), product_path(product, 'ru'), True)
    content += header(lang, product_path(product, tr(lang, 'ru', 'en')), path)
    content += f'''<main id="main-content"><section class="wy-cushion-hero"><div class="shell">{breadcrumb(items, lang)}<div class="product-hero-grid"><div><p class="eyebrow">{tr(lang, 'Window seat cushion collection', 'Коллекция подушек для подоконника')} · {product['reference']}</p><h1>{esc(p['name'])}</h1><p class="product-intro">{esc(p['description'])}</p><p class="wy-status">{tr(lang, 'Custom size · Indoor seating reference · Quote required', 'Индивидуальный размер · Для помещения · Цена по запросу')}</p><div class="product-actions"><a class="button button-dark" href="#quote">{tr(lang, 'Request my quote', 'Запросить расчет')}</a><a class="button button-light" href="#measure">{tr(lang, 'How to measure', 'Как снять размеры')}</a></div><p class="wy-photo-caption">{tr(lang, 'Photo design reference. Final size, fabric, color and included accessories are agreed before ordering.', 'Фото — ориентир дизайна. Итоговые размеры, ткань, цвет и комплектация согласовываются до заказа.')}</p></div><figure class="wy-product-image">{photo(product['style'], p['alt'], True)}<figcaption class="wy-photo-caption">{tr(lang, 'Owner-supplied design reference', 'Фото дизайна, предоставленное продавцом')} · {product['reference']}</figcaption></figure></div></div></section>
<section class="wy-cushion-section"><div class="shell"><p class="eyebrow">{tr(lang, 'Design & specification', 'Дизайн и параметры')}</p><h2>{esc(p['detail_title'])}</h2><p>{esc(p['detail'])}</p><dl class="wy-specs">{''.join(f'<div><dt>{esc(a)}</dt><dd>{esc(b)}</dd></div>' for a, b in specs)}</dl><p>{esc(p['check'])}</p></div></section>'''
    if len(product['photos']) > 1:
        figures = []
        for asset in product['photos']:
            enhanced = asset == 'teddy-window-scene'
            caption = tr(lang, 'AI-enhanced room scene for visual inspiration; use the original reference to confirm product details.', 'Сцена интерьера с обработкой ИИ для визуального ориентира; детали товара уточняйте по исходному фото.') if enhanced else tr(lang, 'Grey corduroy design reference' if asset == 'corduroy-grey' else 'Original design reference', 'Серый вельветовый вариант' if asset == 'corduroy-grey' else 'Исходное фото дизайна')
            alt = tr(lang, 'Grey ribbed corduroy-style window seat cushion' if asset == 'corduroy-grey' else 'AI-enhanced cream teddy cushion window nook' if enhanced else p['alt'], 'Серый вариант подушки с вельветовой фактурой' if asset == 'corduroy-grey' else 'Кремовая подушка тедди у окна, сцена с обработкой ИИ' if enhanced else p['alt'])
            figures.append(f'<figure>{photo(asset, alt, layout="gallery")}<figcaption class="wy-photo-caption">{caption}</figcaption></figure>')
        content += f'<section class="wy-cushion-section wy-tinted"><div class="shell"><h2>{tr(lang, "Compare the photo references", "Сравните варианты на фото")}</h2><div class="wy-photo-grid">' + ''.join(figures) + '</div></div></section>'
    content += measurement(lang) + questions(lang, product) + guide_links(lang) + quote_section(lang, product)
    content += f'<section class="wy-cushion-section"><div class="shell"><h2>{tr(lang, "Explore other cushion designs", "Другие варианты подушек")}</h2><div class="wy-related-grid">' + ''.join(card(other, lang, layout='related') for other in PRODUCTS if other != product) + '</div></div></section>'
    write(path.strip('/') + '/index.html', content + footer(lang))


def build_category(lang):
    path = category_path(lang)
    title = tr(lang, 'Custom Window Seat & Bay Window Cushions | Weieryang', 'Подушки на подоконник и для эркера на заказ | Weieryang')
    name = tr(lang, 'Custom window seat cushions', 'Подушки на подоконник на заказ')
    desc = tr(lang, 'Compare four window seat cushion designs: teddy fleece, corduroy, cotton-linen style and textured woven. Send your dimensions and request a confirmed quote.', 'Четыре варианта подушек для подоконника: тедди, вельвет, фактура хлопка и льна и фактурное плетение. Пришлите размеры для подтвержденного расчета.')
    items = [(tr(lang, '/', '/ru/'), tr(lang, 'Home', 'Главная')), (tr(lang, '/products/', '/ru/products/'), tr(lang, 'Products', 'Товары')), (path, name)]
    listing = {'@type': 'ItemList', 'numberOfItems': len(PRODUCTS), 'itemListElement': [{'@type': 'ListItem', 'position': i + 1, 'url': ORIGIN + product_path(p, lang), 'name': p[lang]['name']} for i, p in enumerate(PRODUCTS)]}
    structured = {'@context': 'https://schema.org', '@graph': [breadcrumb_schema(items), {'@type': 'CollectionPage', '@id': ORIGIN + path, 'url': ORIGIN + path, 'name': name, 'description': desc, 'inLanguage': lang, 'mainEntity': listing}]}
    content = head(lang, path, title, desc, 'teddy-channel-detail', structured, category_path('en'), category_path('ru')) + header(lang, category_path(tr(lang, 'ru', 'en')))
    content += f'''<main id="main-content"><section class="wy-cushion-hero"><div class="shell">{breadcrumb(items, lang)}<div class="product-hero-grid"><div><p class="eyebrow">{tr(lang, 'Window seat & bench cushion collection', 'Коллекция для подоконников и скамей')}</p><h1>{name}</h1><p class="product-intro">{tr(lang, 'Turn the seat by your window into a place to pause. Compare four reference designs, then send the measurements of your window seat, bay window or indoor bench for a cushion quotation tailored to your space.', 'Сделайте место у окна удобным уголком для отдыха. Сравните четыре варианта дизайна и пришлите размеры подоконника, эркера или скамьи для расчета подушки под ваше пространство.')}</p><div class="product-actions"><a class="button button-dark" href="#designs">{tr(lang, 'Choose a cushion design', 'Выбрать дизайн')}</a><a class="button button-light" href="#measure">{tr(lang, 'Measure your seat', 'Снять размеры')}</a></div><p class="wy-status">{tr(lang, '4 design families · Custom and standard-size inquiries · Price confirmed by quote', '4 варианта дизайна · Стандартные и индивидуальные размеры по запросу · Цена после расчета')}</p></div><figure class="wy-product-image">{photo('teddy-channel-detail', PRODUCTS[0][lang]['alt'], True)}<figcaption class="wy-photo-caption">{tr(lang, 'Teddy fleece design reference · WY-WC01', 'Вариант тедди · WY-WC01')}</figcaption></figure></div></div></section>
<section class="wy-cushion-section" id="designs"><div class="shell"><p class="eyebrow">{tr(lang, 'Choose the look', 'Выберите внешний вид')}</p><h2>{tr(lang, 'Four designs for your indoor window seat', 'Четыре дизайна для сиденья у окна')}</h2><p>{tr(lang, 'Start with a fabric appearance and color reference. Each product page explains the design and the details to confirm for your own cushion. Photos do not establish standard dimensions, foam density or fabric composition.', 'Начните с фактуры и цветового ориентира. В каждой карточке описаны дизайн и параметры для согласования. Фото не подтверждают стандартный размер, плотность наполнителя или состав ткани.')}</p><div class="catalog-grid">{''.join(card(p, lang) for p in PRODUCTS)}</div></div></section>'''
    rows = ''.join(f'<tr><th scope="row"><a href="{product_path(p, lang)}">{esc(p[lang]["short"])}</a></th><td>{esc(p[lang]["appearance"])}</td><td>{esc(p[lang]["check"])}</td></tr>' for p in PRODUCTS)
    content += f'<section class="wy-cushion-section wy-tinted"><div class="shell"><h2>{tr(lang, "Compare the window seat cushion designs", "Сравните дизайны подушек")}</h2><div class="wy-comparison"><table><thead><tr><th scope="col">{tr(lang, "Design", "Дизайн")}</th><th scope="col">{tr(lang, "Reference appearance", "Внешний вид")}</th><th scope="col">{tr(lang, "Confirm for your order", "Что уточнить")}</th></tr></thead><tbody>{rows}</tbody></table></div></div></section>'
    content += measurement(lang) + questions(lang) + guide_links(lang) + quote_section(lang)
    write(path.strip('/') + '/index.html', content + footer(lang))


def build_ru_products():
    path = '/ru/products/'
    desc = 'Каталог Weieryang: диваны и кресла для оптовых проектов, а также четыре дизайна подушек на подоконник с расчетом по вашим размерам.'
    structured = {'@context': 'https://schema.org', '@type': 'CollectionPage', 'url': ORIGIN + path, 'name': 'Каталог диванов и подушек Weieryang', 'description': desc, 'inLanguage': 'ru'}
    content = head('ru', path, 'Диваны и подушки на подоконник | Каталог Weieryang', desc, 'corduroy-ivory', structured, '/products/', path) + header('ru', '/products/', path)
    content += '''<main id="main-content"><section class="catalog-hero"><div class="shell"><p class="eyebrow">Каталог Weieryang</p><h1>Диваны и подушки для вашего проекта.</h1><p>Выберите направление: мебель для оптовой поставки или подушка для подоконника по нужным размерам. Существующие страницы диванов и упаковочные данные доступны по прежним адресам.</p><div class="wy-catalog-groups"><a class="wy-catalog-group" href="/ru/compressed-sofa/"><strong>Диваны и сиденья</strong><span>Оптовые модели, OEM и данные упаковки →</span></a><a class="wy-catalog-group" href="/ru/window-seat-cushions/"><strong>Подушки на подоконник</strong><span>4 варианта дизайна · размер и цена по запросу →</span></a></div></div></section><section class="wy-cushion-section"><div class="shell"><h2>Диваны: стартовые модели</h2><div class="catalog-grid">'''
    for slug, name, img in [('fn-011b-compressed-sofa', 'FN-011B · Сжатый диван', 'FN-011B'), ('fn-104-sofa-bed', 'FN-104 · Диван-кровать', 'FN-104'), ('fn-802-floor-sofa', 'FN-802 · Напольный диван', 'FN-802')]:
        content += f'<article class="catalog-card"><a href="/ru/products/{slug}/"><div class="catalog-image"><img src="/assets/images/{img}.webp" alt="{name}" width="900" height="700" loading="lazy"></div><div class="catalog-card-copy"><h3>{name}</h3><p>Размеры, упаковка и запрос оптовой цены →</p></div></a></article>'
    content += '</div><p><a class="button button-light" href="/products/">Все семейства диванов и кресел (EN)</a></p></div></section><section class="wy-cushion-section wy-tinted"><div class="shell"><h2>Подушки на подоконник: четыре дизайна</h2><div class="catalog-grid">' + ''.join(card(p, 'ru') for p in PRODUCTS) + '</div></div></section>'
    write('ru/products/index.html', content + quote_section('ru') + footer('ru'))


def integrate_catalog():
    path = 'products/index.html'
    content = read(path)
    newline = '\r\n' if '\r\n' in content else '\n'
    # Preserve the existing catalog's established search metadata. Cushion keywords
    # belong on the dedicated collection and product pages linked from this catalog.
    content = content.replace('Sofa Families & Custom Window Seat Cushions | Weieryang', 'Sofa Product Families and Seat Configurations | Weieryang Factory')
    content = content.replace('Browse 23 sofa and chair families with 41 configurations, plus 4 custom window seat cushion designs. Compare specifications and request a factory quotation.', 'Browse 23 Weieryang sofa and chair families with 41 seat, size and layout configurations. Compare packing data and open linked buyer guides before sending an RFQ.')
    content = content.replace('Factory-direct sofa families and custom window seat cushions. Compare sofa packing data or choose a cushion design and request a made-to-fit quotation.', 'Factory-direct upholstered furniture families organized by seat count, size and layout configuration, with buyer guides for RFQ, samples and packing.')
    if '/assets/cushion-catalog.css' not in content:
        content = content.replace('</head>', '<link rel="stylesheet" href="/assets/cushion-catalog.css?v=20261006a">' + newline + alternates('/products/', '/ru/products/').replace('\n', newline) + newline + '</head>')
    content = content.replace('<strong>23</strong><span>product families</span>', '<strong>27</strong><span>23 sofa + 4 cushion families</span>')
    content = content.replace('<strong>41</strong><span>available configurations</span>', '<strong>41</strong><span>sofa configurations</span>')
    content = content.replace('<strong>6</strong><span>product categories</span>', '<strong>2</strong><span>main product groups</span>')
    content = content.replace('<strong data-product-count>23 families</strong>', '<strong data-product-count>27 families</strong>')
    content = content.replace('Every original model remains available inside its product family', 'Sofa configurations and cushion designs are organized in separate groups')
    if '<!-- cushion-catalog-groups:start -->' not in content:
        groups = '<!-- cushion-catalog-groups:start --><div class="shell wy-catalog-groups"><a class="wy-catalog-group" href="/products/?group=sofas#sofas-seating"><strong>Sofas &amp; seating</strong><span>23 families · 41 configurations · all six existing sofa / seating categories</span></a><a class="wy-catalog-group" href="/window-seat-cushions/"><strong>Window seat cushions</strong><span>4 designs · custom dimensions · individual quotations →</span></a></div><!-- cushion-catalog-groups:end -->'
        content = content.replace('  <section class="catalog-section">', groups + newline + '  <section class="catalog-section">', 1)
    if 'data-product-filter="window-seat-cushions"' not in content:
        filter_button = '          <button class="filter-button" id="window-seat-cushions" type="button" data-product-filter="window-seat-cushions" aria-pressed="false">Window Seat Cushions &middot; 4</button>'
        needle = '        </div>' + newline + '        <div class="catalog-search">'
        assert needle in content
        content = content.replace(needle, filter_button + newline + needle, 1)
    if 'data-product-filter="sofas-seating"' not in content:
        needle = '<button class="filter-button" type="button" data-product-filter="all" aria-pressed="true">All families</button>'
        content = content.replace(needle, needle + newline + '          <button class="filter-button" id="sofas-seating" type="button" data-product-filter="sofas-seating" aria-pressed="false">Sofas &amp; Seating &middot; 23</button>')
    content = re.sub(r'(data-category=")([^"\n]*)(")', lambda m: m.group(0) if 'window-seat-cushions' in m.group(2) or 'sofas-seating' in m.group(2) else m.group(1) + m.group(2) + ' sofas-seating' + m.group(3), content)
    content = re.sub(r'<!-- cushion-catalog-cards:start -->.*?<!-- cushion-catalog-cards:end -->\r?\n', '', content, flags=re.S)
    needle = '      </div>' + newline + '    </div>' + newline + '  </section>' + newline + '  <section class="product-section product-section-dark"'
    assert needle in content
    cards = '<!-- cushion-catalog-cards:start -->' + newline + newline.join(card(p, 'en').replace('\n', newline) for p in PRODUCTS) + newline + '<!-- cushion-catalog-cards:end -->' + newline
    content = content.replace(needle, cards + needle, 1)
    pattern = r'<script type="application/ld\+json">(.*?)</script>'
    match = re.search(pattern, content, flags=re.S)
    listing = json.loads(match.group(1))
    listing['itemListElement'] = [item for item in listing['itemListElement'] if not any(p['slug'] in item['url'] for p in PRODUCTS)]
    listing['itemListElement'] += [{'@type': 'ListItem', 'position': 24 + i, 'url': ORIGIN + product_path(p, 'en'), 'name': p['en']['name']} for i, p in enumerate(PRODUCTS)]
    listing['numberOfItems'] = 27
    listing['name'] = 'Weieryang Sofa and Window Seat Cushion Product Families'
    content = content[:match.start()] + schema(listing) + content[match.end():]
    if '<a href="/window-seat-cushions/">Window seat cushions</a>' not in content:
        content = content.replace('<a href="/products/#lounge-chair">Lounge chairs</a>', '<a href="/products/#lounge-chair">Lounge chairs</a>' + newline + '      <a href="/window-seat-cushions/">Window seat cushions</a>')
    write(path, content)


def integrate_home_and_discovery():
    changed = []
    for path, old, new in [('index.html', PREVIEW + '/?entry=header-home-en', '/window-seat-cushions/?entry=header-home-en'), ('ru/index.html', PREVIEW + '/ru/?entry=header-home-ru', '/ru/window-seat-cushions/?entry=header-home-ru'), ('index.html', PREVIEW + '/?entry=home-en', '/window-seat-cushions/?entry=home-en'), ('ru/index.html', PREVIEW + '/ru/?entry=home-ru', '/ru/window-seat-cushions/?entry=home-ru')]:
        content = read(path)
        assert old in content or new in content
        updated_content = content.replace(old, new)
        if updated_content != content:
            changed.append(ORIGIN + '/' + path.removesuffix('index.html'))
        write(path, updated_content)
    urls = [ORIGIN + category_path(lang) for lang in ['en', 'ru']] + [ORIGIN + '/ru/products/'] + [ORIGIN + product_path(p, lang) for p in PRODUCTS for lang in ['en', 'ru']] + [ORIGIN + guide_path(g, lang) for g in GUIDES for lang in ['en', 'ru']]
    sitemap = read('sitemap.xml')
    for url in urls:
        if '<loc>' + url + '</loc>' not in sitemap:
            entry = f'  <url><loc>{url}</loc><lastmod>{DATA["updated"]}</lastmod><changefreq>monthly</changefreq><priority>0.70</priority></url>\n'
            sitemap = sitemap.replace('</urlset>', entry + '</urlset>')
    # Existing lastmod describes actual HTML changes, not a catalog rebuild.
    changed_urls = [ORIGIN + '/' + path.removesuffix('index.html') for path in CHANGED_HTML]
    for url in set(changed + changed_urls):
        pattern = r'(<loc>' + re.escape(url) + r'</loc><lastmod>)[^<]+(</lastmod>)'
        sitemap = re.sub(pattern, lambda m: m.group(1) + DATA['updated'] + m.group(2), sitemap)
    write('sitemap.xml', sitemap)
    llms = read('llms.txt')
    if '\n## Window Seat Cushion Collection\n' in llms:
        llms = llms.split('\n## Window Seat Cushion Collection\n')[0].rstrip() + '\n'
    llms = llms.rstrip() + '\n'
    llms += '\n## Window Seat Cushion Collection\n'
    llms += 'Weieryang also has a separate quote-based indoor window seat and bench cushion collection. The sofa catalog and its packing specifications remain separate. Four photo-reference design families are available for inquiry; finished size, foam, fabric composition, color, accessories, shipping, production time and payment terms require quotation confirmation. There are no confirmed online prices or stock assertions for these photo designs.\n'
    llms += f'- English collection: {ORIGIN}/window-seat-cushions/\n- Russian collection: {ORIGIN}/ru/window-seat-cushions/\n- Russian product catalog: {ORIGIN}/ru/products/\n'
    for p in PRODUCTS:
        llms += f'- {p["reference"]} {p["en"]["name"]}: {ORIGIN}{product_path(p, "en")}\n'
        llms += f'- {p["reference"]} {p["ru"]["name"]}: {ORIGIN}{product_path(p, "ru")}\n'
    for g in GUIDES:
        for lang in ['en', 'ru']:
            llms += f'- {g[lang]["name"]}: {ORIGIN}{guide_path(g, lang)}\n'
    llms += 'For a cushion quotation, provide the catalog reference, preferred photo, all seating-area dimensions, finished thickness, front drop if requested, quantity, destination country and postal code. Cotton-linen style describes appearance, not a certified fiber composition. AI-enhanced scenes are labeled and excluded from the Product schema image list.\n'
    write('llms.txt', llms)


if __name__ == '__main__':
    for language in ['en', 'ru']:
        build_category(language)
        for product in PRODUCTS:
            build_product(product, language)
        for guide in GUIDES:
            build_guide(guide, language)
    build_ru_products()
    integrate_catalog()
    integrate_home_and_discovery()
    print('Built 4 cushion designs × 2 languages, 2 collections, 4 buying guides and 1 Russian catalog; preserved original sofa details.')
